language: go

go:
 - 1.12.x
 - master

before_install:
 - go get github.com/theodesp/unionfind

go:
   - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
