language: go

go:
 - 1.12.x
 - master

before_install:
 - go get gonum.org/v1/gonum/...
 - go get gonum.org/v1/plot/...
 - go get github.com/kettek/apng
 - go get github.com/theodesp/unionfind
 - go build ./...

go:
   - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
